version: '3'
services:
  api:
    container_name: ${APP_NAME}
    image: ${APP_NAME}
    build: .
    command: ["npm", "run", "dev"]
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/usr/src/app
      - '/usr/src/app/node_modules'
